[[function-config]]
name = "releaseDeposit"
inputs = [
    { name = "account", type = "address" },
    { name = "value", type = "uint256" },
]

[[function-config]]
name = "revokeDeposit"
inputs = [
    { name = "account", type = "address" },
    { name = "value", type = "uint256" },
]

