[[function-config]]
name = "deposit"
inputs = [
    { name = "account", type = "address" },
    { name = "value", type = "uint256" },
]

[[function-config]]
name = "unregister"
inputs = [
    { name = "wallet", type = "address" },
]

[[ethtoken-config]]
name = "register"
inputs = [
    { name = "addr", type = "address" },
    { name = "uuid", type = "bytes32" },
]
