---
version: "2.1"
services:
  "vault-middleware":
    build:
      context: middleware
    restart: "always"
    ports:
      - ${VAULT_PORT_MAP:?'Vault Port Mapping'}
    networks:
      "bridge-net":
        ipv4_address: 10.0.10.10
    command: "--host 0.0.0.0 --port 8080 http://10.0.10.6:8080 http://10.0.10.8:8080"
  vault:
    environment:
      - NODE_CONNECT_TIMEOUT
      - NODE_REQUEST_TIMEOUT 
      - NODE_MAX_IDLE
    build:
      context: "vault-signer"
    restart: "always"
    volumes:
      - "vault-state:/signer"
    networks:
      "bridge-net":
        ipv4_address: 10.0.10.6
    command: "--node-addr ${HC_NODE_WS:?'Node WebSocket API Endpoint'} --default-contract ${HC_CONTRACT:?'HubCulture Contract Address'}"
networks:
  "bridge-net":
    ipam:
      config:
        - gateway: 10.0.10.1
          subnet: 10.0.10.1/24
volumes:
  "vault-state": {}
